#ifndef FILE_SEARCH_ARCTIC_H
#define FILE_SEARCH_ARCTIC_H

/* DEFINE EXIT STATUS FOR NO INPUT CASE AND INVALID INPUT CASE.
 * NO INPUT CASE TRIGGERS WHEN argc == 1.
 * INVALID INPUT CASE TRIGGERS WHEN FILES DO NOT EXIST OR ARE NOT READABLE
 */
 
#define EXIT_NO_INPUT 2
#define EXIT_INVALID_INPUT 3

/* THIS FUNCTION ENSURES THAT ALL FILES EXIST AND ARE READABLE 
 * AND ALL FILES PASSED CONTAINS USABLE DATA TO PERFORM THE 
 * SEARCH. THIS IS DONE BY CONFIRMING FILE CRITERIA PROVIDED IN
 * ASSIGNMENT 3. PLEASE CHECK THE CORRESPONDING .c IMPLEMENTATION 
 * FOR MORE DETAILS.
 */
 
extern unsigned int verify_search_arctic_text_files(int, char **);


#endif

