#ifndef SEARCH_ARCTIC_FIND_MATCH_H
#define SEARCH_ARCTIC_FIND_MATCH_H


/* DEFINE SUBSYSTEM CONSTANTS  */
#define MATCHED 0
#define NOT_MATCHED 1

/* FUNCTION THAT TAKES SEARCH IMAGE, ITS ROW AND COLUMN  
 * AS WELL AS TAKES ARCTIC IMAGE, ITS ROW AND COLUMN
 * AS INPUTS AND RETURNS AN INTEGER THAT SHOWS THE NUMBER
 * OF MATCHES.
 */
extern int search_arctic_find_match(char **,int,int,char **,int,int);



#endif
