#ifndef FILE_EXIST_READABLE_H
#define FILE_EXIST_READABLE_H


/* DEFINE EXIT STATUS FOR NO INPUT CASE AND INVALID INPUT CASE.
 * NO INPUT CASE TRIGGERS WHEN argc == 1.
 * INVALID INPUT CASE TRIGGERS WHEN FILES DO NOT EXIST OR ARE NOT READABLE
 */
#define EXIT_NO_INPUT 2
#define EXIT_INVALID_INPUT 3

/* THIS FUNCTION ENSURES THAT ALL FILES EXIST AND ARE READABLE */
extern unsigned int verify_files_exist_and_readable(int, char **);


#endif

